# Generated by Django 4.1.2 on 2022-10-19 10:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import users.utils


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_initial_data_groups'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecretKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default=users.utils.get_secret_key, editable=False, max_length=128, unique=True, verbose_name='Ключ')),
                ('partner', models.ForeignKey(limit_choices_to={'role': 3}, on_delete=django.db.models.deletion.CASCADE, related_name='secret_keys', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь (партнёр)')),
            ],
        ),
    ]
