# Generated by Django 4.1.2 on 2022-10-22 07:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_secretkey'),
    ]

    operations = [
        migrations.AddField(
            model_name='secretkey',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Время создания'),
            preserve_default=False,
        ),
    ]
