# Generated by Django 4.1.2 on 2022-10-22 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_secretkey_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaluser',
            name='confirmed',
            field=models.BooleanField(default=False, verbose_name='Подтверждён?'),
        ),
        migrations.AlterField(
            model_name='user',
            name='confirmed',
            field=models.BooleanField(default=False, verbose_name='Подтверждён?'),
        ),
    ]
