# Generated by Django 4.1.2 on 2022-10-23 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('role_permissions', '0002_initial_data_roles'),
        ('users', '0005_alter_historicaluser_confirmed_alter_user_confirmed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='role_permissions.userrole', verbose_name='Роль пользователя'),
        ),
    ]
