# Generated by Django 4.1.2 on 2022-10-24 12:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models
import users.utils


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_historicaluser_options_alter_user_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalEncryptionKey',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('key', models.CharField(db_index=True, default=users.utils.get_encryprion_key, editable=False, max_length=64, verbose_name='Ключ')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='Время редактирования')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('partner', models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'role': 3}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь (партнёр)')),
            ],
            options={
                'verbose_name': 'historical encryption key',
                'verbose_name_plural': 'historical encryption keys',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='EncryptionKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default=users.utils.get_encryprion_key, editable=False, max_length=64, unique=True, verbose_name='Ключ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время редактирования')),
                ('partner', models.OneToOneField(limit_choices_to={'role': 3}, on_delete=django.db.models.deletion.CASCADE, related_name='encryption_keys', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь (партнёр)')),
            ],
        ),
        migrations.AddIndex(
            model_name='encryptionkey',
            index=models.Index(fields=['partner'], name='users_encry_partner_1141f5_idx'),
        ),
    ]
