# Generated by Django 4.1.2 on 2022-10-24 13:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_historicalencryptionkey_encryptionkey_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encryptionkey',
            name='partner',
            field=models.OneToOneField(limit_choices_to={'role': 3}, on_delete=django.db.models.deletion.CASCADE, related_name='encryption_key', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь (партнёр)'),
        ),
    ]
