# Generated by Django 4.1.2 on 2022-10-26 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_encryptionkey_partner'),
    ]

    operations = [
        migrations.AddField(
            model_name='secretkey',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='Доступен?'),
        ),
        migrations.AddField(
            model_name='secretkey',
            name='name',
            field=models.CharField(default='Test API', max_length=32, verbose_name='Название'),
            preserve_default=False,
        ),
    ]
