# Generated by Django 4.1.2 on 2022-10-18 12:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finances', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalcard',
            old_name='role',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='card',
            name='role',
        ),
        migrations.AddField(
            model_name='card',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Время создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='card',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Время редактирования'),
        ),
        migrations.AddField(
            model_name='card',
            name='user',
            field=models.ForeignKey(default=1, limit_choices_to={'role': 3}, on_delete=django.db.models.deletion.CASCADE, related_name='cards', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь (партнёр)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalcard',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, verbose_name='Время создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalcard',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, verbose_name='Время редактирования'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='card',
            name='number',
            field=models.BigIntegerField(unique=True, verbose_name='Номер карты'),
        ),
        migrations.AlterField(
            model_name='historicalcard',
            name='number',
            field=models.BigIntegerField(db_index=True, verbose_name='Номер карты'),
        ),
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время редактирования')),
                ('uid', models.UUIDField(editable=False, unique=True, verbose_name='UUID')),
                ('payment_type', models.CharField(choices=[('replenishment', 'пополнение'), ('withdrawl', 'списание')], max_length=32, verbose_name='Статус')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Сумма')),
                ('comission', models.DecimalField(decimal_places=2, default=0.04, max_digits=4, verbose_name='Ставка комиссии')),
                ('comission_amount', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Сумма комиссии')),
                ('status', models.CharField(choices=[('new', 'новый'), ('pending', 'в ожидании обработки'), ('processing', 'в обработке'), ('failed', 'не прошёл'), ('successfull', 'проведён успешно')], max_length=32, verbose_name='Статус')),
                ('operator', models.ForeignKey(limit_choices_to={'role': 2}, on_delete=django.db.models.deletion.CASCADE, related_name='handled_payrolls', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь (партнёр)')),
                ('partner', models.ForeignKey(limit_choices_to={'role': 3}, on_delete=django.db.models.deletion.CASCADE, related_name='payrolls', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь (партнёр)')),
            ],
            options={
                'verbose_name': 'Платежное поручение',
                'verbose_name_plural': 'Платежные поручения',
            },
        ),
        migrations.CreateModel(
            name='HistoricalPayroll',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='Время редактирования')),
                ('uid', models.UUIDField(db_index=True, editable=False, verbose_name='UUID')),
                ('payment_type', models.CharField(choices=[('replenishment', 'пополнение'), ('withdrawl', 'списание')], max_length=32, verbose_name='Статус')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Сумма')),
                ('comission', models.DecimalField(decimal_places=2, default=0.04, max_digits=4, verbose_name='Ставка комиссии')),
                ('comission_amount', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Сумма комиссии')),
                ('status', models.CharField(choices=[('new', 'новый'), ('pending', 'в ожидании обработки'), ('processing', 'в обработке'), ('failed', 'не прошёл'), ('successfull', 'проведён успешно')], max_length=32, verbose_name='Статус')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('operator', models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'role': 2}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь (партнёр)')),
                ('partner', models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'role': 3}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь (партнёр)')),
            ],
            options={
                'verbose_name': 'historical Платежное поручение',
                'verbose_name_plural': 'historical Платежные поручения',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
