# Generated by Django 4.1.2 on 2022-10-18 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0002_rename_role_historicalcard_user_remove_card_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpayroll',
            name='card',
            field=models.BigIntegerField(default=1111111111111111, verbose_name='Номер карты'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payroll',
            name='card',
            field=models.BigIntegerField(default=1, verbose_name='Номер карты'),
            preserve_default=False,
        ),
    ]
