# Generated by Django 4.1.2 on 2022-10-18 12:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finances', '0003_historicalpayroll_card_payroll_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpayroll',
            name='operator',
            field=models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'role': 2}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь (оператор)'),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='operator',
            field=models.ForeignKey(limit_choices_to={'role': 2}, on_delete=django.db.models.deletion.CASCADE, related_name='handled_payrolls', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь (оператор)'),
        ),
    ]
