# Generated by Django 4.1.2 on 2022-10-18 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0004_alter_historicalpayroll_operator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpayroll',
            name='payment_type',
            field=models.CharField(choices=[('replenishment', 'пополнение'), ('withdrawl', 'списание')], max_length=32, verbose_name='Вид платежа'),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='payment_type',
            field=models.CharField(choices=[('replenishment', 'пополнение'), ('withdrawl', 'списание')], max_length=32, verbose_name='Вид платежа'),
        ),
    ]
