# Generated by Django 4.1.2 on 2022-10-18 12:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0005_alter_historicalpayroll_payment_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpayroll',
            name='uid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID'),
        ),
    ]
