# Generated by Django 4.1.2 on 2022-10-19 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0007_historicalaccount_account'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payroll',
            options={'permissions': [('can_handle_payroll_', 'Может проводить или отклонять платёж')], 'verbose_name': 'Платежное поручение', 'verbose_name_plural': 'Платежные поручения'},
        ),
        migrations.AlterField(
            model_name='historicalpayroll',
            name='status',
            field=models.CharField(choices=[('new', 'новый'), ('pending', 'в ожидании обработки'), ('processing', 'в обработке'), ('failed', 'не прошёл'), ('successful', 'проведён успешно')], default='new', max_length=32, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='status',
            field=models.CharField(choices=[('new', 'новый'), ('pending', 'в ожидании обработки'), ('processing', 'в обработке'), ('failed', 'не прошёл'), ('successful', 'проведён успешно')], default='new', max_length=32, verbose_name='Статус'),
        ),
    ]
