# Generated by Django 4.1.2 on 2022-10-22 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0010_alter_historicalpayroll_operator_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalpayroll',
            old_name='card',
            new_name='card_number',
        ),
        migrations.RenameField(
            model_name='payroll',
            old_name='card',
            new_name='card_number',
        ),
        migrations.AddField(
            model_name='historicalpayroll',
            name='performed',
            field=models.BooleanField(default=False, editable=False, verbose_name='проведён?'),
        ),
        migrations.AddField(
            model_name='payroll',
            name='performed',
            field=models.BooleanField(default=False, editable=False, verbose_name='проведён?'),
        ),
    ]
