# Generated by Django 4.1.2 on 2022-10-22 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0011_rename_card_historicalpayroll_card_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpayroll',
            name='remittance_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Сумма к переводу'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payroll',
            name='remittance_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Сумма к переводу'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='account',
            name='balance',
            field=models.PositiveIntegerField(default=0, verbose_name='Баланс'),
        ),
        migrations.AlterField(
            model_name='historicalaccount',
            name='balance',
            field=models.PositiveIntegerField(default=0, verbose_name='Баланс'),
        ),
        migrations.AlterField(
            model_name='historicalpayroll',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Сумма в запросе'),
        ),
        migrations.AlterField(
            model_name='historicalpayroll',
            name='card_number',
            field=models.PositiveBigIntegerField(verbose_name='Номер карты'),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Сумма в запросе'),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='card_number',
            field=models.PositiveBigIntegerField(verbose_name='Номер карты'),
        ),
    ]
