# Generated by Django 4.1.2 on 2022-10-23 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0013_alter_account_user_alter_payroll_operator_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='user',
        ),
        migrations.RemoveField(
            model_name='historicalcard',
            name='user',
        ),
    ]
