# Generated by Django 4.1.2 on 2022-10-23 14:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0014_remove_card_user_remove_historicalcard_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.DecimalValidator, django.core.validators.MinValueValidator], verbose_name='Баланс'),
        ),
        migrations.AlterField(
            model_name='historicalaccount',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.DecimalValidator, django.core.validators.MinValueValidator], verbose_name='Баланс'),
        ),
    ]
