# Generated by Django 4.1.2 on 2022-10-24 08:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finances', '0015_alter_account_balance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время редактирования')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(verbose_name='Кодовое название')),
            ],
            options={
                'verbose_name': 'Банк',
                'verbose_name_plural': 'Банки',
            },
        ),
        migrations.CreateModel(
            name='HistoricalBank',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='Время редактирования')),
                ('name', models.CharField(db_index=True, max_length=128, verbose_name='Название')),
                ('slug', models.SlugField(verbose_name='Кодовое название')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical Банк',
                'verbose_name_plural': 'historical Банки',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddIndex(
            model_name='card',
            index=models.Index(fields=['number', 'is_active'], name='finances_ca_number_7e59b9_idx'),
        ),
        migrations.AddIndex(
            model_name='payroll',
            index=models.Index(fields=['operator', 'status'], name='finances_pa_operato_c7a334_idx'),
        ),
        migrations.AddIndex(
            model_name='payroll',
            index=models.Index(fields=['uid'], name='finances_pa_uid_852925_idx'),
        ),
        migrations.AddIndex(
            model_name='payroll',
            index=models.Index(fields=['partner'], name='finances_pa_partner_9a801e_idx'),
        ),
        migrations.AddField(
            model_name='historicalbank',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='card',
            name='bank',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cards', to='finances.bank', verbose_name='Банк'),
        ),
        migrations.AddField(
            model_name='historicalcard',
            name='bank',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='finances.bank', verbose_name='Банк'),
        ),
    ]
