# Generated by Django 4.1.2 on 2022-10-25 20:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finances', '0016_bank_historicalbank_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='operator',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 2}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attached_cards', to=settings.AUTH_USER_MODEL, verbose_name='Оператор'),
        ),
        migrations.AddField(
            model_name='historicalcard',
            name='operator',
            field=models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'role': 2}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Оператор'),
        ),
    ]
