# Generated by Django 4.1.2 on 2022-10-27 11:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0017_card_operator_historicalcard_operator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.DecimalValidator, django.core.validators.MinValueValidator(0)], verbose_name='Баланс'),
        ),
        migrations.AlterField(
            model_name='historicalaccount',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.DecimalValidator, django.core.validators.MinValueValidator(0)], verbose_name='Баланс'),
        ),
        migrations.AlterField(
            model_name='historicalpayroll',
            name='card_number',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Номер карты'),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='card_number',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Номер карты'),
        ),
    ]
