# Generated by Django 4.1.2 on 2022-11-05 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0020_alter_card_current_turnover_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpayroll',
            name='cheque',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Скан чека'),
        ),
        migrations.AddField(
            model_name='payroll',
            name='cheque',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/', verbose_name='Скан чека'),
        ),
    ]
