# Generated by Django 4.1.2 on 2022-11-07 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0021_historicalpayroll_cheque_payroll_cheque'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payroll',
            name='cheque',
            field=models.ImageField(blank=True, null=True, upload_to='api/uploads/%Y/%m/%d/', verbose_name='Скан чека'),
        ),
    ]
