# Generated by Django 4.1.2 on 2022-11-11 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0023_alter_payroll_cheque'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpayroll',
            name='bank',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='finances.bank', verbose_name='Банк'),
        ),
        migrations.AddField(
            model_name='payroll',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='card_payrolls', to='finances.bank', verbose_name='Банк'),
        ),
    ]
