# Generated by Django 4.1.2 on 2022-11-29 13:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0024_historicalpayroll_bank_payroll_bank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.DecimalValidator(10, 2), django.core.validators.MinValueValidator(0)], verbose_name='Баланс'),
        ),
        migrations.AlterField(
            model_name='historicalaccount',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.DecimalValidator(10, 2), django.core.validators.MinValueValidator(0)], verbose_name='Баланс'),
        ),
    ]
