# Generated by Django 4.1.2 on 2022-11-15 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0024_historicalpayroll_bank_payroll_bank'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpayroll',
            name='account_number',
            field=models.PositiveBigIntegerField(blank=True, help_text='Для QIWI - номер телефона в формате 79119000000', null=True, verbose_name='Номер банковского счёта'),
        ),
        migrations.AddField(
            model_name='payroll',
            name='account_number',
            field=models.PositiveBigIntegerField(blank=True, help_text='Для QIWI - номер телефона в формате 79119000000', null=True, verbose_name='Номер банковского счёта'),
        ),
    ]
