# Generated by Django 4.1.2 on 2022-12-03 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0025_alter_account_balance_and_more'),
        ('finances', '0026_alter_account_balance_and_more'),
    ]

    operations = [
    ]
