# Generated by Django 4.1.2 on 2022-12-05 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0026_alter_account_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpayroll',
            name='back_url',
            field=models.URLField(blank=True, max_length=256, verbose_name='URL для возврата пользователя'),
        ),
        migrations.AddField(
            model_name='payroll',
            name='back_url',
            field=models.URLField(blank=True, max_length=256, verbose_name='URL для возврата пользователя'),
        ),
    ]
