# Generated by Django 4.1.2 on 2022-12-05 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0027_historicalpayroll_back_url_payroll_back_url'),
        ('finances', '0027_merge_20221203_1248'),
    ]

    operations = [
    ]
