# Generated by Django 4.1.2 on 2022-12-15 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0028_merge_20221205_2111'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpayroll',
            name='file_cheque',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Документ с чеком'),
        ),
        migrations.AddField(
            model_name='payroll',
            name='file_cheque',
            field=models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/', verbose_name='Документ с чеком'),
        ),
    ]
